# Generated by Django 5.2.9 on 2026-03-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(default='Cameroun', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='gallery_images',
            field=models.TextField(blank=True, help_text="Liste d'URLs ou chemins d'images separes par virgule ou retour ligne."),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
